name: Build holdings

permissions:
  contents: write

on:
  push:
    paths:
      - "data/activity.csv"
      - "data/activity-feed-export_*.csv"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate holdings.csv
        run: |
          python -m pip install --upgrade pip
          python scripts/build_holdings.py

      # Archive AFTER generating holdings
      - name: Archive input CSV(s)
        shell: bash
        run: |
          set -euo pipefail
          set -x
          mkdir -p data/archive
          shopt -s nullglob
          found=0
          for f in data/activity.csv data/activity-feed-export_*.csv; do
            if [ -f "$f" ]; then
              found=1
              ts=$(date -u +%Y%m%d_%H%M%S)
              base=$(basename "$f" | tr ' ' '_' )
              dest="data/archive/${ts}__${base}"
              echo "Archiving $f -> $dest"
              git mv "$f" "$dest" || mv "$f" "$dest"
            fi
          done
          if [ "$found" -eq 0 ]; then
            echo "No activity files found to archive."
          fi

      - name: Debug status before commit
        shell: bash
        run: |
          set -x
          echo "=== git status ==="
          git status --porcelain=v1
          echo "=== tree ==="
          ls -la
          echo "=== data ==="
          ls -la data || true
          echo "=== data/archive ==="
          ls -la data/archive || true

      # Commit ALL changes (don’t rely on file_pattern globs)
      - name: Commit holdings and archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update holdings.csv and archive input"
          add_options: --all
          # no file_pattern => commit all staged/changed files
          branch: ${{ github.ref_name }}
