name: Build holdings

permissions:
  contents: write

on:
  push:
    paths:
      - "data/activity.csv"
      - "data/activity-feed-export_*.csv"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate holdings.csv
        run: |
          python -m pip install --upgrade pip
          python scripts/build_holdings.py

      # NEW: archive any activity files regardless of name
      - name: Archive input CSV(s)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data/archive
          shopt -s nullglob
          for f in data/activity.csv data/activity-feed-export_*.csv; do
            if [ -f "$f" ]; then
              ts=$(date -u +%Y%m%d_%H%M%S)
              base=$(basename "$f" | tr ' ' '_' )
              mv "$f" "data/archive/${ts}__${base}"
              echo "Archived $f -> data/archive/${ts}__${base}"
            fi
          done

      - name: Commit holdings and archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update holdings.csv and archive input"
          file_pattern: |
            data/holdings.csv
            data/archive/**
          # IMPORTANT: stage deletions (the moved activity file disappears from /data)
          add_options: --all
          branch: ${{ github.ref_name }}
